import type { Lesson } from '@core/types/lesson.js';
import type { SubjectModule } from '@core/types/subject.js';
import type { TopicGraph } from '@core/types/topic.js';

/**
 * Printable worksheet + formula sheet generator (Phase 12).
 * Produces print-friendly HTML from lessons and topic graphs.
 * No special dependencies — prints via browser "Save as PDF".
 */

const BASE_CSS = `
  body { font-family: Georgia, "Times New Roman", serif; max-width: 780px; margin: 1rem auto; padding: 0 1.2rem; color: #111; line-height: 1.55; }
  h1 { border-bottom: 2px solid #111; padding-bottom: 0.3em; margin-bottom: 0.5em; }
  h2 { color: #333; margin-top: 2em; border-bottom: 1px solid #ccc; padding-bottom: 0.2em; }
  .q { margin: 1.2em 0; padding: 0.8em 1em; border-left: 3px solid #333; background: #fafafa; page-break-inside: avoid; }
  .q-number { font-weight: bold; color: #666; font-size: 0.85em; }
  .prompt { margin: 0.3em 0; }
  .answer-line { border-bottom: 1px solid #999; display: inline-block; min-width: 200px; height: 1.2em; vertical-align: middle; }
  .choices { list-style: upper-alpha; padding-left: 1.8em; margin: 0.4em 0; }
  .choices li { margin: 0.2em 0; }
  .formula { background: #f5f5f5; border: 1px solid #ddd; padding: 0.6em 1em; margin: 0.5em 0; border-radius: 4px; font-family: "Cambria Math", Cambria, serif; }
  .footer { margin-top: 3em; color: #888; font-size: 0.8em; text-align: center; border-top: 1px solid #ccc; padding-top: 1em; }
  @media print {
    body { max-width: 100%; }
    .q { page-break-inside: avoid; }
  }
`;

export class PrintEngine {
  /** Generate a worksheet HTML from a set of lessons' assessments. */
  generateWorksheet(lessons: Lesson[], title = 'Worksheet'): string {
    const questions: { lesson: Lesson; q: NonNullable<Lesson['assessment']>['questions'][number]; n: number }[] = [];
    let n = 1;
    for (const lesson of lessons) {
      if (!lesson.assessment) continue;
      for (const q of lesson.assessment.questions) {
        questions.push({ lesson, q, n: n++ });
      }
    }

    const body = questions.map(({ lesson, q, n }) => `
      <div class="q">
        <div class="q-number">Q${n} · ${lesson.topic}</div>
        <div class="prompt">${esc(q.prompt)}</div>
        ${q.type === 'mcq' && q.choices ? `
          <ol class="choices">
            ${q.choices.map(c => `<li>${esc(c)}</li>`).join('')}
          </ol>
        ` : `
          <div>Answer: <span class="answer-line">&nbsp;</span></div>
        `}
      </div>
    `).join('');

    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(title)}</title>
  <style>${BASE_CSS}</style>
</head>
<body>
  <h1>${esc(title)}</h1>
  ${questions.length === 0 ? '<p>No questions in the selected lessons.</p>' : body}
  <div class="footer">Generated by Study. ${questions.length} question${questions.length === 1 ? '' : 's'}.</div>
</body>
</html>`;
  }

  /** Generate a formula sheet HTML from a subject's topic graph.
   *  Formulas are extracted from lesson titles/objectives — a richer version
   *  would pull from a dedicated knowledge bank. */
  generateFormulaSheet(subject: SubjectModule, lessons: Lesson[]): string {
    const topicGroups = new Map<string, Lesson[]>();
    for (const l of lessons) {
      if (l.subject !== subject.id) continue;
      const rootTopic = l.topic.split('.')[0]!;
      const arr = topicGroups.get(rootTopic) ?? [];
      arr.push(l);
      topicGroups.set(rootTopic, arr);
    }

    const sections = [...topicGroups.entries()].map(([root, ls]) => {
      const node = subject.topics.nodes[root];
      return `
        <h2>${esc(node?.title ?? root)}</h2>
        ${ls.map(l => `
          <div class="formula">
            <strong>${esc(l.title)}</strong>
            ${l.meta.objectives && l.meta.objectives.length > 0
              ? `<ul>${l.meta.objectives.map(o => `<li>${esc(o)}</li>`).join('')}</ul>`
              : ''}
          </div>
        `).join('')}
      `;
    }).join('');

    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(subject.displayName)} Formula Sheet</title>
  <style>${BASE_CSS}</style>
</head>
<body>
  <h1>${esc(subject.displayName)} — Formula Sheet</h1>
  ${sections || '<p>No content available for this subject.</p>'}
  <div class="footer">Generated by Study.</div>
</body>
</html>`;
  }

  /** Generate printable revision notes from a topic graph (all topics listed). */
  generateRevisionNotes(subject: SubjectModule): string {
    const walk = (graph: TopicGraph, nodeId: string, depth: number): string => {
      const node = graph.nodes[nodeId];
      if (!node) return '';
      const indent = '  '.repeat(depth);
      let out = `${indent}<li><strong>${esc(node.title)}</strong>`;
      if (node.children && node.children.length > 0) {
        out += `<ul>${node.children.map(c => walk(graph, c, depth + 1)).join('')}</ul>`;
      }
      out += '</li>';
      return out;
    };
    const topList = subject.topics.roots.map(r => walk(subject.topics, r, 0)).join('');
    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>${esc(subject.displayName)} Revision Notes</title>
  <style>${BASE_CSS} ul { line-height: 1.8; } </style>
</head>
<body>
  <h1>${esc(subject.displayName)} — Revision Outline</h1>
  <ul>${topList}</ul>
  <div class="footer">Generated by Study.</div>
</body>
</html>`;
  }
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
}
